---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: content-discovery
  name: content-discovery-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-discovery-app
  template:
    metadata:
      labels:
        app: content-discovery-app
    spec:
      containers:
      - name: app
        image: content_discovery:latest
        readinessProbe:
          httpGet:
            path: /api/health
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: CONTENT_DISCOVERY_HOST
          value: "0.0.0.0"
        - name: CONTENT_DISCOVERY_WORKERS_COUNT
          value: "10"
        - name: CONTENT_DISCOVERY_DB_HOST
          value: "content-discovery-db-service"
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
          name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: content-discovery
  name: content-discovery-app-service
spec:
  selector:
    app: content-discovery-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: api-port
    name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: content-discovery-app
  namespace: content-discovery
  labels:
    name: content-discovery-app
spec:
  rules:
  - host: content-discovery.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: content-discovery-app-service
            port:
              name: api-port

---
