---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: content-discovery-luiscusihuaman
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        stack.okteto.com/name: content-discovery
        stack.okteto.com/service: api
    spec:
      containers:
      - name: api
        image: $OKTETO_BUILD_API_IMAGE
        imagePullPolicy: Always
        env:
        - name: CONTENT_DISCOVERY_CONTENT_DISCOVERY_URL
          value: http://api.identity-socializer-luiscusihuaman:8000
        - name: CONTENT_DISCOVERY_DB_BASE
          value: content_discovery
        - name: CONTENT_DISCOVERY_DB_HOST
          value: db
        - name: CONTENT_DISCOVERY_DB_PASS
          value: content_discovery
        - name: CONTENT_DISCOVERY_DB_PORT
          value: "5432"
        - name: CONTENT_DISCOVERY_DB_USER
          value: content_discovery
        - name: CONTENT_DISCOVERY_ENVIRONMENT
          value: dev
        - name: CONTENT_DISCOVERY_HOST
          value: 0.0.0.0
        - name: CONTENT_DISCOVERY_PORT
          value: "9000"
        - name: CONTENT_DISCOVERY_RELOAD
          value: "True"
---
apiVersion: v1
kind: Service
metadata:
  namespace: content-discovery-luiscusihuaman
  name: api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
