version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "9000:9000"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      CONTENT_DISCOVERY_RELOAD: "True"
  db:
    ports:
      # Exposes database port.
    - "5433:5432"