"""empty message

Revision ID: c068b416ebd7
Revises: 075d6047b474
Create Date: 2023-10-13 14:21:15.516965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c068b416ebd7'
down_revision = '075d6047b474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
