"""empty message

Revision ID: 3057f3af0689
Revises: b0d71cdb713d
Create Date: 2023-10-13 14:23:13.697497

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3057f3af0689"
down_revision = "b0d71cdb713d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
