"""empty message

Revision ID: 17c72e4df351
Revises: 5dc2a44b23db
Create Date: 2023-11-02 16:30:11.202519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "17c72e4df351"
down_revision = "5dc2a44b23db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snaps", sa.Column("visibility", sa.INTEGER(), default=1))
    op.alter_column("snaps", "likes", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("snaps", "shares", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("snaps", "favs", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("fk_snap_parent_id", "snaps", type_="foreignkey")
    op.create_foreign_key(None, "snaps", "snaps", ["parent_id"], ["id"])
    op.execute("UPDATE snaps SET visibility = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_snap_parent_id",
        "snaps",
        "snaps",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("snaps", "favs", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("snaps", "shares", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("snaps", "likes", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("snaps", "visibility")
    # ### end Alembic commands ###
