"""empty message

Revision ID: b0d71cdb713d
Revises: c068b416ebd7
Create Date: 2023-10-13 14:22:44.868218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0d71cdb713d"
down_revision = "c068b416ebd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
